[package]
name = "mathx"
version = "0.1.0"
edition = "2021"

[features]
default = ["no_std"]
# default = []
no_std = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
